av1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include("cars.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cars/urls.py
from django.urls import path
from .views import CarListView, CarDetailView

urlpatterns = [
    path("", CarListView.as_view(), name="list-cars"),
    path("<int:pk>/", CarDetailView.as_view(), name="detail-car"),
]

carscommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("cars/", include("cars.urls"))
]

core/urls.py
from django.urls import path
from .views import RegisterView, UserLoginView, UserLogoutView

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('', UserLoginView.as_view(), name="login"),
    path('logout/', UserLogoutView.as_view(), name="logout"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("funcionarios/", include("funcionarios.urls")),
]

funcionarios/urls.py
from django.urls import path
from .views import DepartamentoListView

urlpatterns = [
    path("", DepartamentoListView.as_view()),
]

cars/models.py
from django.db import models

# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return f"{self.name}"


class Car(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    model = models.CharField(max_length=100)
    price = models.DecimalField(max_digits= 9, decimal_places=2)

    def __str__(self) -> str:
        return f"{self.model}"

core/models.py
from django.db import models

funcionarios/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from ecommerce.my_fields import BRCPFFieldNumeric
from .validators.datefield import validate_lt_date

ESTADOS_CIVIS = [
    ("S", "Solteiro"),
    ("C", "Casado"),
    ("D", "Divorciado"),
    ("V", "Viúvo"),
]

# Create your models here.
class Funcionario(models.Model):
    """Model dos funcionários da empresa."""

    nome = models.CharField(max_length=200)
    salario = models.FloatField(validators=[MinValueValidator(0.0)])
    cpf = BRCPFFieldNumeric("CPF")

    def __str__(self) -> str:
        return f"{self.nome}"


class Perfil(models.Model):
    """Model dos perfis dos funcionário."""

    funcionario = models.OneToOneField(
        Funcionario, on_delete=models.CASCADE, primary_key=True
    )
    nome_social = models.CharField(max_length=200)
    estado_civil = models.CharField(max_length=1, choices=ESTADOS_CIVIS)
    data_nascimento = models.DateField(validators=[validate_lt_date])

    @property
    def idade(self) -> int:
        return timezone.now().year - self.data_nascimento.year

    def __str__(self) -> str:
        return f"{self.nome_social}"


class Departamento(models.Model):
    """Modelo dos departamentos dos funcionários."""

    nome = models.CharField(max_length=200)
    funcionarios = models.ManyToManyField(Funcionario, related_name="funcionarios")
    descricao = models.CharField("Descrição", max_length=500)

    def __str__(self) -> str:
        return f"{self.nome}"

core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm


class UserForm(forms.ModelForm):
    """ Form used to register user."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    password = forms.CharField(widget=forms.PasswordInput(), label="Sua senha")

    class Meta:
        model = User
        fields = ["username", "email", "password"]
        labels = {
            "username": "Seu usuário",
            "email": "Seu email",
            "password": "Sua senha",
        }


class LoginForm(AuthenticationForm):
    """ Form used to login user. """

    def __init__(self, *args,  request=None, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    username = forms.CharField(label="Seu Usuário")
    password = forms.CharField(
        label="Sua senha",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )

cars/views.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Car


class CarListView(LoginRequiredMixin, ListView):
    model = Car
    template_name = "list_cars.html"
    context_object_name = "obj_list"
    login_url = reverse_lazy("login")


class CarDetailView(LoginRequiredMixin, DetailView):
    model = Car
    template_name = "detail_cars.html"
    login_url = reverse_lazy("login")

core/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from .forms import LoginForm, UserForm


class RegisterView(SuccessMessageMixin, FormView):

    template_name = "registration.html"
    form_class = UserForm
    success_url = reverse_lazy("login")
    success_message = "Cadastro realizado com sucesso."

    def form_valid(self, form):
        user = User.objects.create_user(
            username=form.cleaned_data["username"],
            email=form.cleaned_data["email"],
            password=form.cleaned_data["password"],
        )
        return super().form_valid(form)


class UserLoginView(SuccessMessageMixin, LoginView):

    template_name = "login.html"
    form_class = LoginForm
    redirect_authenticated_user = True
    next_page = reverse_lazy("list-cars")
    success_message = "Login realizado com sucesso."

class UserLogoutView(LogoutView):
    next_page = reverse_lazy("login")

funcionarios/views.py
from django.views.generic import ListView
from .models import Departamento


class DepartamentoListView(ListView):
    """View que lista os departamentos e seus respectivos funcionarios."""

    queryset = Departamento.objects.all().prefetch_related('funcionarios')
    template_name = "list_funcionario.html"

cars/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link href="{% static 'styles.css'%}" rel="stylesheet" >
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <title>Carros</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href={% url "list_carros" %}>Carros</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href={% url "list_carros" %}>Listagem</a>
              </li>
          </div>
        </div>
    </nav>
    <main>
        {% block content %} {% endblock %}
    </main>
    <div class="container-fluid">
        <footer class="py-3 my-4">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href={% url "list_carros" %} class="nav-link px-2 text-muted">Listagem</a></li>
          </ul>
          <p class="text-center text-muted">&copy; 2022 Carros, Inc</p>
        </footer>
      </div>
</body>
</html>

cars/templates/detail_cars.html
{% extends "base.html" %}

{% block content %}
<div class ="container-fluid">
    <div class="row py-3">
        <div class="col-md">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title">{{ object.brand }} {{ object.model }}</h5>
                  <h1>R${{ object.price|floatformat:"2g" }}</h1>
                  <div class="text-center">
                      <a href="" class="btn btn-secondary btn-lg">Comprar</a>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

cars/templates/detalhe_carros.html
{% extends "base.html" %}

{% block content %} 
<div class ="container-fluid">
    <div class="row py-3">
        <div class="col-md">
            <div class="card">
                <div class="text-center">
                    <img class="card-img-top" src={{ obj.imagem }} alt="">
                </div>
                <div class="card-body">
                  <h5 class="card-title">{{ obj.marca }} {{ obj.modelo }}</h5>
                  <p class="card-text">{{ obj.descricao }}</p>
                  <h1>R${{ obj.preco|floatformat:"2g" }}</h1>
                  <div class="text-center">
                      <a href="" class="btn btn-secondary btn-lg">Comprar</a>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

cars/templates/list_carros.html
{% extends "base.html" %}

{% block content %} 
<div class ="container-fluid">
    <div class="row py-3">
        {%for carro in obj_list %} 
        <div class="col-md">
            <div class="card">
                <img class="card-img-top" src={{ carro.imagem}} alt="">
                <div class="card-body">
                  <h5 class="card-title">{{ carro.marca }} {{ carro.modelo }}</h5>
                  <p class="card-text"><h1>R${{ carro.preco|floatformat:"2g" }}</h1></p>
                  <div class="text-center">
                      <a href={% url "detalhe_carro" forloop.counter0 %} class="btn btn-secondary btn-lg">Comprar</a>
                  </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{%endblock%}
    

cars/templates/list_cars.html
{% extends "base.html" %}
{% block content %}
<div class ="container-fluid">
    <div class="row py-3">
        {% regroup obj_list by brand as brands_list %}
        {% for brand in brands_list %}
            <h1 class="text-center p-4"> {{brand.grouper}} </h1>
            {% for carro in brand.list %}
            <div class="col-md">
                <div class="card">
                    <div class="card-body">
                    <h5 class="card-title">{{ carro.brand }} {{ carro.model }}</h5>
                    <p class="card-text"><h1>R${{ carro.price|floatformat:"2g" }}</h1></p>
                    <div class="text-center">
                        <a href={% url "detail-car" carro.id %} class="btn btn-secondary btn-lg">Comprar</a>
                    </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        {% endfor %}
    </div>
</div>
{% endblock content %}

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Cars</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Cars</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url "list-cars" %}">Listagem</a>
              </li>
            </ul>
            <li class="nav-item d-flex">
              <a class="nav-link"  tabindex="-1">
                {% if user.is_authenticated %}
                    {{ user.get_username }}
                {% else %}
                    <a href="{% url "login" %}">Por favor, faça o log in.</a>
                {% endif %}
              </a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item d-flex">
                        <a href="{% url "logout" %}">Sair.</a>
                    </a>
                </li>
            {% endif %}
          </div>
        </div>
    </nav>

    {% if messages %}
        <div class="row">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% block content %}
    {% endblock content %}

</body>
</html>

core/templates/login.html
{% extends "base.html" %}
{% block content %}
<section class="vh-100">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Entrar</p>

                  <form class="mx-1 mx-md-4"  method="post">
                    {% csrf_token %}
                    {% for field in form %}
                      <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                          {{ field }}

                          {% if field.errors %}
                            {% for error in field.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                          {% endif %}

                          {{ field.label }}
                        </div>
                      </div>
                    {% endfor %}
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <input type="submit" class="btn btn-primary btn-lg" value="Entrar">
                    </div>
                  </form>
                  <div class="text-center">
                      <a href="{% url "register" %}"> Cadastre-se </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock content %}

core/templates/registration.html
{% extends "base.html" %}
{% block content %}
<section class="vh-100">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Registrar</p>

                  <form class="mx-1 mx-md-4"  method="post">
                    {% csrf_token %}
                    {% for field in form %}
                      <div class="d-flex flex-row align-items-center mb-4">
                        <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                        <div class="form-outline flex-fill mb-0">
                          {{ field }}

                          {% if field.errors %}
                            {% for error in field.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                          {% endif %}

                          {{ field.label }}
                        </div>
                      </div>
                    {% endfor %}
                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                      <input type="submit" class="btn btn-primary btn-lg" value="Registrar-se">
                    </div>
                  </form>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock content %}

funcionarios/templates/list_funcionario.html
{% load my_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <title>Funcionarios</title>
</head>
<body>
    {% for departamento in  object_list %}
        <h1 class="text-center">{{ departamento.nome }}</h1>
        <h4 class="text-center">{{ departamento.descricao }}</h3>
        <table class="table">
            <tr>
              <th>Nome</th>
              <th>Salario</th>
              <th>CPF</th>
              <th>Nome social</th>
              <th>Estado civil</th>
              <th>Idade</th>
            </tr>
            {% for funcionario in departamento.funcionarios.all %}
            <tr>
                <td>{{funcionario.nome}}</td>
                <td>{{funcionario.salario}}</td>
                <td>{{ funcionario.cpf | cpf_formatter}}</td>
                <td>{{funcionario.perfil.nome_social}}</td>
                <td>{{funcionario.perfil.get_estado_civil_display}}</td>
                <td>{{funcionario.perfil.idade}}</td>
            </tr>
            {% endfor %}

          </table>
    {% endfor %}

</body>
</html>